// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: protos/medal-service/medal.proto

package medalspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MedalType int32

const (
	MedalType_GOLD   MedalType = 0
	MedalType_SILVER MedalType = 1
	MedalType_BRONZE MedalType = 2
)

// Enum value maps for MedalType.
var (
	MedalType_name = map[int32]string{
		0: "GOLD",
		1: "SILVER",
		2: "BRONZE",
	}
	MedalType_value = map[string]int32{
		"GOLD":   0,
		"SILVER": 1,
		"BRONZE": 2,
	}
)

func (x MedalType) Enum() *MedalType {
	p := new(MedalType)
	*p = x
	return p
}

func (x MedalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MedalType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_medal_service_medal_proto_enumTypes[0].Descriptor()
}

func (MedalType) Type() protoreflect.EnumType {
	return &file_protos_medal_service_medal_proto_enumTypes[0]
}

func (x MedalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MedalType.Descriptor instead.
func (MedalType) EnumDescriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{0}
}

type Medal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId string    `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,3,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt string    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string    `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64     `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Medal) Reset() {
	*x = Medal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Medal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medal) ProtoMessage() {}

func (x *Medal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medal.ProtoReflect.Descriptor instead.
func (*Medal) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{0}
}

func (x *Medal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Medal) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *Medal) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *Medal) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Medal) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *Medal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Medal) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Medal) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

// Create
type CreateMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryId string    `protobuf:"bytes,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,2,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,4,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
}

func (x *CreateMedalRequest) Reset() {
	*x = CreateMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedalRequest) ProtoMessage() {}

func (x *CreateMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedalRequest.ProtoReflect.Descriptor instead.
func (*CreateMedalRequest) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMedalRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateMedalRequest) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *CreateMedalRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateMedalRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

type CreateMedalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId string    `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,3,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt string    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string    `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64     `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *CreateMedalResponse) Reset() {
	*x = CreateMedalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedalResponse) ProtoMessage() {}

func (x *CreateMedalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedalResponse.ProtoReflect.Descriptor instead.
func (*CreateMedalResponse) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMedalResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateMedalResponse) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateMedalResponse) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *CreateMedalResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateMedalResponse) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *CreateMedalResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateMedalResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateMedalResponse) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

// Read by ID
type GetMedalByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMedalByIdRequest) Reset() {
	*x = GetMedalByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalByIdRequest) ProtoMessage() {}

func (x *GetMedalByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMedalByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{3}
}

func (x *GetMedalByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMedalByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId string    `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,3,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt string    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string    `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64     `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *GetMedalByIdResponse) Reset() {
	*x = GetMedalByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalByIdResponse) ProtoMessage() {}

func (x *GetMedalByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMedalByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{4}
}

func (x *GetMedalByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMedalByIdResponse) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *GetMedalByIdResponse) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *GetMedalByIdResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetMedalByIdResponse) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *GetMedalByIdResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetMedalByIdResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetMedalByIdResponse) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

// Read all medals
type GetMedalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medals []*Medal `protobuf:"bytes,1,rep,name=medals,proto3" json:"medals,omitempty"`
}

func (x *GetMedalsResponse) Reset() {
	*x = GetMedalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsResponse) ProtoMessage() {}

func (x *GetMedalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsResponse.ProtoReflect.Descriptor instead.
func (*GetMedalsResponse) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{5}
}

func (x *GetMedalsResponse) GetMedals() []*Medal {
	if x != nil {
		return x.Medals
	}
	return nil
}

// Read by filter
type GetMedalByFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryId string    `protobuf:"bytes,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,2,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,4,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
}

func (x *GetMedalByFilterRequest) Reset() {
	*x = GetMedalByFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalByFilterRequest) ProtoMessage() {}

func (x *GetMedalByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetMedalByFilterRequest) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{6}
}

func (x *GetMedalByFilterRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *GetMedalByFilterRequest) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *GetMedalByFilterRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetMedalByFilterRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

type GetMedalByFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medals []*Medal `protobuf:"bytes,1,rep,name=medals,proto3" json:"medals,omitempty"`
}

func (x *GetMedalByFilterResponse) Reset() {
	*x = GetMedalByFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalByFilterResponse) ProtoMessage() {}

func (x *GetMedalByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalByFilterResponse.ProtoReflect.Descriptor instead.
func (*GetMedalByFilterResponse) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{7}
}

func (x *GetMedalByFilterResponse) GetMedals() []*Medal {
	if x != nil {
		return x.Medals
	}
	return nil
}

// Update
type UpdateMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId string    `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,3,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
}

func (x *UpdateMedalRequest) Reset() {
	*x = UpdateMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedalRequest) ProtoMessage() {}

func (x *UpdateMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedalRequest.ProtoReflect.Descriptor instead.
func (*UpdateMedalRequest) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMedalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMedalRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *UpdateMedalRequest) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *UpdateMedalRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateMedalRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

type UpdateMedalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId string    `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type      MedalType `protobuf:"varint,3,opt,name=type,proto3,enum=MedalType" json:"type,omitempty"`
	EventId   string    `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AthleteId string    `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt string    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string    `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64     `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *UpdateMedalResponse) Reset() {
	*x = UpdateMedalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedalResponse) ProtoMessage() {}

func (x *UpdateMedalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedalResponse.ProtoReflect.Descriptor instead.
func (*UpdateMedalResponse) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMedalResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMedalResponse) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *UpdateMedalResponse) GetType() MedalType {
	if x != nil {
		return x.Type
	}
	return MedalType_GOLD
}

func (x *UpdateMedalResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateMedalResponse) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *UpdateMedalResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateMedalResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateMedalResponse) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

// Delete
type DeleteMedalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMedalRequest) Reset() {
	*x = DeleteMedalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedalRequest) ProtoMessage() {}

func (x *DeleteMedalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedalRequest.ProtoReflect.Descriptor instead.
func (*DeleteMedalRequest) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMedalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMedalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteMedalResponse) Reset() {
	*x = DeleteMedalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedalResponse) ProtoMessage() {}

func (x *DeleteMedalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedalResponse.ProtoReflect.Descriptor instead.
func (*DeleteMedalResponse) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMedalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Void message for empty requests
type VoidMedal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoidMedal) Reset() {
	*x = VoidMedal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_medal_service_medal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoidMedal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidMedal) ProtoMessage() {}

func (x *VoidMedal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_medal_service_medal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidMedal.ProtoReflect.Descriptor instead.
func (*VoidMedal) Descriptor() ([]byte, []int) {
	return file_protos_medal_service_medal_proto_rawDescGZIP(), []int{12}
}

var File_protos_medal_service_medal_proto protoreflect.FileDescriptor

var file_protos_medal_service_medal_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x64, 0x22, 0xfb, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xfc, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x33, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x6d,
	0x65, 0x64, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64,
	0x22, 0x3a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06,
	0x6d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x22, 0x9d, 0x01, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x22, 0xfb, 0x01, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x0b, 0x0a, 0x09, 0x56, 0x6f, 0x69, 0x64, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x2a, 0x2d,
	0x0a, 0x09, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x4f, 0x4c, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4c, 0x56, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x52, 0x4f, 0x4e, 0x5a, 0x45, 0x10, 0x02, 0x32, 0xef, 0x02,
	0x0a, 0x0c, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x13, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x13, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x12, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x12, 0x0a, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x61, 0x6c, 0x42, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x42,
	0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x64,
	0x61, 0x6c, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_medal_service_medal_proto_rawDescOnce sync.Once
	file_protos_medal_service_medal_proto_rawDescData = file_protos_medal_service_medal_proto_rawDesc
)

func file_protos_medal_service_medal_proto_rawDescGZIP() []byte {
	file_protos_medal_service_medal_proto_rawDescOnce.Do(func() {
		file_protos_medal_service_medal_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_medal_service_medal_proto_rawDescData)
	})
	return file_protos_medal_service_medal_proto_rawDescData
}

var file_protos_medal_service_medal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_medal_service_medal_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_medal_service_medal_proto_goTypes = []interface{}{
	(MedalType)(0),                   // 0: MedalType
	(*Medal)(nil),                    // 1: Medal
	(*CreateMedalRequest)(nil),       // 2: CreateMedalRequest
	(*CreateMedalResponse)(nil),      // 3: CreateMedalResponse
	(*GetMedalByIdRequest)(nil),      // 4: GetMedalByIdRequest
	(*GetMedalByIdResponse)(nil),     // 5: GetMedalByIdResponse
	(*GetMedalsResponse)(nil),        // 6: GetMedalsResponse
	(*GetMedalByFilterRequest)(nil),  // 7: GetMedalByFilterRequest
	(*GetMedalByFilterResponse)(nil), // 8: GetMedalByFilterResponse
	(*UpdateMedalRequest)(nil),       // 9: UpdateMedalRequest
	(*UpdateMedalResponse)(nil),      // 10: UpdateMedalResponse
	(*DeleteMedalRequest)(nil),       // 11: DeleteMedalRequest
	(*DeleteMedalResponse)(nil),      // 12: DeleteMedalResponse
	(*VoidMedal)(nil),                // 13: VoidMedal
}
var file_protos_medal_service_medal_proto_depIdxs = []int32{
	0,  // 0: Medal.type:type_name -> MedalType
	0,  // 1: CreateMedalRequest.type:type_name -> MedalType
	0,  // 2: CreateMedalResponse.type:type_name -> MedalType
	0,  // 3: GetMedalByIdResponse.type:type_name -> MedalType
	1,  // 4: GetMedalsResponse.medals:type_name -> Medal
	0,  // 5: GetMedalByFilterRequest.type:type_name -> MedalType
	1,  // 6: GetMedalByFilterResponse.medals:type_name -> Medal
	0,  // 7: UpdateMedalRequest.type:type_name -> MedalType
	0,  // 8: UpdateMedalResponse.type:type_name -> MedalType
	2,  // 9: MedalService.CreateMedal:input_type -> CreateMedalRequest
	9,  // 10: MedalService.UpdateMedal:input_type -> UpdateMedalRequest
	11, // 11: MedalService.DeleteMedal:input_type -> DeleteMedalRequest
	4,  // 12: MedalService.GetMedalById:input_type -> GetMedalByIdRequest
	13, // 13: MedalService.GetMedals:input_type -> VoidMedal
	7,  // 14: MedalService.GetMedalByFilter:input_type -> GetMedalByFilterRequest
	3,  // 15: MedalService.CreateMedal:output_type -> CreateMedalResponse
	10, // 16: MedalService.UpdateMedal:output_type -> UpdateMedalResponse
	12, // 17: MedalService.DeleteMedal:output_type -> DeleteMedalResponse
	5,  // 18: MedalService.GetMedalById:output_type -> GetMedalByIdResponse
	6,  // 19: MedalService.GetMedals:output_type -> GetMedalsResponse
	8,  // 20: MedalService.GetMedalByFilter:output_type -> GetMedalByFilterResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_protos_medal_service_medal_proto_init() }
func file_protos_medal_service_medal_proto_init() {
	if File_protos_medal_service_medal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_medal_service_medal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Medal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMedalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalByFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalByFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMedalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMedalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMedalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_medal_service_medal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoidMedal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_medal_service_medal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_medal_service_medal_proto_goTypes,
		DependencyIndexes: file_protos_medal_service_medal_proto_depIdxs,
		EnumInfos:         file_protos_medal_service_medal_proto_enumTypes,
		MessageInfos:      file_protos_medal_service_medal_proto_msgTypes,
	}.Build()
	File_protos_medal_service_medal_proto = out.File
	file_protos_medal_service_medal_proto_rawDesc = nil
	file_protos_medal_service_medal_proto_goTypes = nil
	file_protos_medal_service_medal_proto_depIdxs = nil
}
