// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: protos/medal-service/medal.proto

package medalspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MedalService_CreateMedal_FullMethodName      = "/MedalService/CreateMedal"
	MedalService_UpdateMedal_FullMethodName      = "/MedalService/UpdateMedal"
	MedalService_DeleteMedal_FullMethodName      = "/MedalService/DeleteMedal"
	MedalService_GetMedalById_FullMethodName     = "/MedalService/GetMedalById"
	MedalService_GetMedals_FullMethodName        = "/MedalService/GetMedals"
	MedalService_GetMedalByFilter_FullMethodName = "/MedalService/GetMedalByFilter"
)

// MedalServiceClient is the client API for MedalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MedalServiceClient interface {
	CreateMedal(ctx context.Context, in *CreateMedalRequest, opts ...grpc.CallOption) (*CreateMedalResponse, error)
	UpdateMedal(ctx context.Context, in *UpdateMedalRequest, opts ...grpc.CallOption) (*UpdateMedalResponse, error)
	DeleteMedal(ctx context.Context, in *DeleteMedalRequest, opts ...grpc.CallOption) (*DeleteMedalResponse, error)
	GetMedalById(ctx context.Context, in *GetMedalByIdRequest, opts ...grpc.CallOption) (*GetMedalByIdResponse, error)
	GetMedals(ctx context.Context, in *VoidMedal, opts ...grpc.CallOption) (*GetMedalsResponse, error)
	GetMedalByFilter(ctx context.Context, in *GetMedalByFilterRequest, opts ...grpc.CallOption) (*GetMedalByFilterResponse, error)
}

type medalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMedalServiceClient(cc grpc.ClientConnInterface) MedalServiceClient {
	return &medalServiceClient{cc}
}

func (c *medalServiceClient) CreateMedal(ctx context.Context, in *CreateMedalRequest, opts ...grpc.CallOption) (*CreateMedalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMedalResponse)
	err := c.cc.Invoke(ctx, MedalService_CreateMedal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalServiceClient) UpdateMedal(ctx context.Context, in *UpdateMedalRequest, opts ...grpc.CallOption) (*UpdateMedalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMedalResponse)
	err := c.cc.Invoke(ctx, MedalService_UpdateMedal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalServiceClient) DeleteMedal(ctx context.Context, in *DeleteMedalRequest, opts ...grpc.CallOption) (*DeleteMedalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMedalResponse)
	err := c.cc.Invoke(ctx, MedalService_DeleteMedal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalServiceClient) GetMedalById(ctx context.Context, in *GetMedalByIdRequest, opts ...grpc.CallOption) (*GetMedalByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedalByIdResponse)
	err := c.cc.Invoke(ctx, MedalService_GetMedalById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalServiceClient) GetMedals(ctx context.Context, in *VoidMedal, opts ...grpc.CallOption) (*GetMedalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedalsResponse)
	err := c.cc.Invoke(ctx, MedalService_GetMedals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalServiceClient) GetMedalByFilter(ctx context.Context, in *GetMedalByFilterRequest, opts ...grpc.CallOption) (*GetMedalByFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedalByFilterResponse)
	err := c.cc.Invoke(ctx, MedalService_GetMedalByFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedalServiceServer is the server API for MedalService service.
// All implementations must embed UnimplementedMedalServiceServer
// for forward compatibility
type MedalServiceServer interface {
	CreateMedal(context.Context, *CreateMedalRequest) (*CreateMedalResponse, error)
	UpdateMedal(context.Context, *UpdateMedalRequest) (*UpdateMedalResponse, error)
	DeleteMedal(context.Context, *DeleteMedalRequest) (*DeleteMedalResponse, error)
	GetMedalById(context.Context, *GetMedalByIdRequest) (*GetMedalByIdResponse, error)
	GetMedals(context.Context, *VoidMedal) (*GetMedalsResponse, error)
	GetMedalByFilter(context.Context, *GetMedalByFilterRequest) (*GetMedalByFilterResponse, error)
	mustEmbedUnimplementedMedalServiceServer()
}

// UnimplementedMedalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMedalServiceServer struct {
}

func (UnimplementedMedalServiceServer) CreateMedal(context.Context, *CreateMedalRequest) (*CreateMedalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMedal not implemented")
}
func (UnimplementedMedalServiceServer) UpdateMedal(context.Context, *UpdateMedalRequest) (*UpdateMedalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMedal not implemented")
}
func (UnimplementedMedalServiceServer) DeleteMedal(context.Context, *DeleteMedalRequest) (*DeleteMedalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedal not implemented")
}
func (UnimplementedMedalServiceServer) GetMedalById(context.Context, *GetMedalByIdRequest) (*GetMedalByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedalById not implemented")
}
func (UnimplementedMedalServiceServer) GetMedals(context.Context, *VoidMedal) (*GetMedalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedals not implemented")
}
func (UnimplementedMedalServiceServer) GetMedalByFilter(context.Context, *GetMedalByFilterRequest) (*GetMedalByFilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedalByFilter not implemented")
}
func (UnimplementedMedalServiceServer) mustEmbedUnimplementedMedalServiceServer() {}

// UnsafeMedalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedalServiceServer will
// result in compilation errors.
type UnsafeMedalServiceServer interface {
	mustEmbedUnimplementedMedalServiceServer()
}

func RegisterMedalServiceServer(s grpc.ServiceRegistrar, srv MedalServiceServer) {
	s.RegisterService(&MedalService_ServiceDesc, srv)
}

func _MedalService_CreateMedal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMedalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServiceServer).CreateMedal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedalService_CreateMedal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServiceServer).CreateMedal(ctx, req.(*CreateMedalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedalService_UpdateMedal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMedalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServiceServer).UpdateMedal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedalService_UpdateMedal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServiceServer).UpdateMedal(ctx, req.(*UpdateMedalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedalService_DeleteMedal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMedalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServiceServer).DeleteMedal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedalService_DeleteMedal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServiceServer).DeleteMedal(ctx, req.(*DeleteMedalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedalService_GetMedalById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedalByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServiceServer).GetMedalById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedalService_GetMedalById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServiceServer).GetMedalById(ctx, req.(*GetMedalByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedalService_GetMedals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidMedal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServiceServer).GetMedals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedalService_GetMedals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServiceServer).GetMedals(ctx, req.(*VoidMedal))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedalService_GetMedalByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedalByFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServiceServer).GetMedalByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedalService_GetMedalByFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServiceServer).GetMedalByFilter(ctx, req.(*GetMedalByFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MedalService_ServiceDesc is the grpc.ServiceDesc for MedalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MedalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MedalService",
	HandlerType: (*MedalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMedal",
			Handler:    _MedalService_CreateMedal_Handler,
		},
		{
			MethodName: "UpdateMedal",
			Handler:    _MedalService_UpdateMedal_Handler,
		},
		{
			MethodName: "DeleteMedal",
			Handler:    _MedalService_DeleteMedal_Handler,
		},
		{
			MethodName: "GetMedalById",
			Handler:    _MedalService_GetMedalById_Handler,
		},
		{
			MethodName: "GetMedals",
			Handler:    _MedalService_GetMedals_Handler,
		},
		{
			MethodName: "GetMedalByFilter",
			Handler:    _MedalService_GetMedalByFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/medal-service/medal.proto",
}
